services:
  onenav:
    container_name: ${CONTAINER_NAME}
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    volumes:
      - ./data:/data/wwwroot/default/data
    image: helloz/onenav:0.9.34
    restart:
      always
    labels:
        createdBy: Apps
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true
