version: '3.9'
services:
  subconverter:
    container_name: ${CONTAINER_NAME}
    image: tindy2013/subconverter:latest
    ports:
      - "${PANEL_APP_PORT_HTTP}:25500"
    restart: always
    labels:
        createdBy: Apps
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true