version: '3'
services:
  playedu:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - ./data/logs/nginx:/var/log/nginx
    ports:
      - "${PANEL_APP_PORT_HTTP}:9800"
      - "${PANEL_APP_PORT_HTTP2}:9700"
      - "${PANEL_APP_PORT_HTTP3}:9801"
      - "${PANEL_APP_PORT_HTTP4}:9900"
    environment:
      - DB_HOST=${PANEL_DB_HOST:-127.0.0.1}
      - DB_PORT=${PANEL_DB_PORT:-3306}
      - DB_NAME=${PANEL_DB_NAME:-playedu}
      - DB_USER=${PANEL_DB_USER:-playedu}
      - DB_PASS=${PANEL_DB_USER_PASSWORD}
      - REDIS_HOST=${PANEL_REDIS_HOST:-6379}
      - REDIS_PORT=${PANEL_REDIS_PORT:-127.0.0.1}
      - REDIS_PASS=${PANEL_REDIS_PASSWORD}
      - SA_TOKEN_JWT_SECRET_KEY=${PLAYEDU_JWT_KEY:-playeduxyz}
    image: registry.cn-hangzhou.aliyuncs.com/playedu/light:1.3
    labels:  
      createdBy: "Apps"
networks:  
  1panel-network:  
    external: true
