version: '3.8'
services:
  meting:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    image: intemd/meting-api:latest
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
