additionalProperties:
  key: traefik   #应用的 key ，仅限英文，用于在 Linux 创建文件夹
  name: Traefik  #应用名称
  tags:
    - Tool #应用标签，可以有多个，请参照下方的标签列表
  shortDescZh: Traefik 是一款 open-source 边缘路由器，可让您轻松地发布服务. 它接收来自您的系统请求，并找出负责处理它们的后端服务组件。 #应用中文描述，不要超过30个字
  shortDescEn: Traefik is an open-source Edge Router that makes publishing your services a fun and easy experience. #应用英文描述
  type: tool  #应用类型，区别于应用分类，只能有一个，请参照下方的类型列表
  crossVersionUpdate: false  #是否可以跨大版本升级
  limit: 0 #应用安装数量限制，0 代表无限制
  website: https://doc.traefik.io/traefik/ #官网地址
  github: https://github.com/traefik/traefik #github 地址
  document: https://doc.traefik.io/traefik/ #文档地址