version: "3.8"
services:
  qbittorrent:
    container_name: ${CONTAINER_NAME}
    image: lscr.io/linuxserver/qbittorrent:4.6.3
    environment:
      - TZ=Asia/Shanghai
      - WEBUI_PORT=${PANEL_APP_PORT_HTTP}
      - TORRENTING_PORT=${TORRENTING_PORT}
    volumes:
      - ./config:/config
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
      - ${TORRENTING_PORT}:${TORRENTING_PORT}
      - ${TORRENTING_PORT}:${TORRENTING_PORT}/udp
    restart: unless-stopped
    labels:
        createdBy: Apps
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true