version: '3'
services:
  mtabserver:
    image: itushan/mtab:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    user: "0"
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - "./data:/app"
    labels:  
      createdBy: "Apps"

networks:  
  1panel-network:  
    external: true
